name: my-firtst-ci-cd-pipeline
on:
  pull_request: 
    branches:
      - main
  push:
    branches:
      - main
  
  jobs:
    manual_test_pipeline:
      runs-on: ubuntu-latest
      steps:
        -name: checkout code
          uses: actions/checkout@v3
        -name: run test   
          run: echo "this is my first ci cd pipeline"
